// Generated by CoffeeScript 1.7.1
(function() {
  var JobItem;

  JobItem = (function() {
    function JobItem(urlList) {
      if ((urlList != null) && urlList.length > 0) {
        this.urlList = urlList;
        this.time = Date.now();
      } else {
        throw new Error("A JobItem requires a urlList.");
      }
    }

    JobItem.prototype.isIdenticalTo = function(otherItem) {
      return (this.urlList.length === otherItem.urlList.length) && this.urlList.every(function(element, index) {
        return element === otherItem.urlList[index];
      });
    };

    return JobItem;

  })();

  module.exports = JobItem;

}).call(this);
