// Generated by CoffeeScript 1.7.1
(function() {
  var ProgressManager,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ProgressManager = (function() {
    function ProgressManager() {
      this.getPercentComplete = __bind(this.getPercentComplete, this);
      this.isInProgress = __bind(this.isInProgress, this);
    }

    ProgressManager.prototype.isInProgress = function(background) {
      if (background == null) {
        throw new Error("A background page object is required.");
      }
      return background.TOTAL_IMAGE_COUNT > 0;
    };

    ProgressManager.prototype.getPercentComplete = function(background) {
      var fractionComplete;
      if (background == null) {
        throw new Error("A background page object is required.");
      }
      fractionComplete = background.UPLOADED_IMAGE_LIST.length / background.TOTAL_IMAGE_COUNT;
      return Math.round(100 * fractionComplete);
    };

    return ProgressManager;

  })();

  module.exports = ProgressManager;

}).call(this);
