// Generated by CoffeeScript 1.7.1
(function() {
  var ProgressManager, expect;

  expect = require('chai').expect;

  ProgressManager = require('../js/ProgressManager.js');

  describe('ProgressManager', function() {
    var pm;
    pm = null;
    beforeEach(function() {
      return pm = new ProgressManager();
    });
    it('should throw an error if either function is not passed a background object', function() {
      expect(function() {
        return pm.isInProgress();
      }).to["throw"](Error, /A background page object is required./);
      return expect(function() {
        return pm.getPercentComplete();
      }).to["throw"](Error, /A background page object is required./);
    });
    it('should correctly determine whether an operation is in progress', function() {
      var background;
      background = {
        TOTAL_IMAGE_COUNT: 0
      };
      expect(pm.isInProgress(background)).to.be["false"];
      background.TOTAL_IMAGE_COUNT = 1;
      return expect(pm.isInProgress(background)).to.be["true"];
    });
    return it('should correctly calculate percentage complete', function() {
      var background;
      background = {
        TOTAL_IMAGE_COUNT: 10,
        UPLOADED_IMAGE_LIST: [0, 0, 0]
      };
      expect(pm.getPercentComplete(background)).to.equal(30);
      background.UPLOADED_IMAGE_LIST.push(0);
      return expect(pm.getPercentComplete(background)).to.equal(40);
    });
  });

}).call(this);
